# Server Port
server.port=8083

# Spring Logging Level
logging.level.org.springframework=info

# Project Logging Level
logging.level.com.cognizant.springlearn3=debug

# Console Logging Pattern
logging.pattern.console=%d{yyMMdd}|%d{HH:mm:ss.SSS}|%-20.20thread|%5p|%-25.25logger{25}|%25M|%m%n